# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Bot Auto Approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'hc-github-team-consul-core'
    steps:
      - uses: hmarr/auto-approve-action@44888193675f29a83e04faf4002fa8c0b537b1e4 # v3.2.1
        with:
          review-message: "Auto approved Consul Bot automated PR"
          github-token: ${{ secrets.MERGE_APPROVE_TOKEN }}
