# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# This workflow checks that the BUSL license is not mentioned anywhere in
# a PR targeting a release that should maintain the MPL-2.0 license.
name: License Checker

on:
  pull_request:
    types: [opened]
    branches:
      - release/1.14.*
      - release/1.15.*
      - release/1.16.*

jobs:
  # checks that the diff does not contain any reference to
  # the BUSL license and thus retains the MPL-2.0 license
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # by default the checkout action doesn't checkout all branches
      - name: Check for BUSL text in diff
        run: ./.github/scripts/license_checker.sh
