# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Trigger OSS to Enterprise Merge
on: 
  pull_request:
  # pull_request_target:
    # types:
    #   - closed
    # branches:
    #   - main
    #   - 'release/*.*.x'

jobs:
  trigger-oss-merge:
    # run this only on merge events in OSS repo
    # if: ${{ github.event.pull_request.merged && github.repository == 'hashicorp/consul' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Merge
        env:
          GIT_REF: ${{ github.ref_name }}
          GIT_SHA: ${{ github.sha }}
          GH_PAT: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
          GIT_ACTOR: ${{ github.actor }}
          GIT_ASSIGNEES: ${{ join(github.event.pull_request.assignees, ',') }}
        run: |
          echo "github: ${{ toJson(github) }}"
          echo "env: ${{ toJson(env) }}"
          echo "blah"
          # curl -H "Authorization: token $GH_PAT" \
          #   -H 'Accept: application/json' \
          #   -d "{\"event_type\": \"oss-merge\", \"client_payload\": {\"git-ref\": \"${GIT_REF}\", \"git-sha\": \"${GIT_SHA}\", \"git-actor\": \"${GIT_ACTOR}\" }}, \"git-assignees\": \"${GIT_ASSIGNEES}\" }}" \
          #   "https://api.github.com/repos/hashicorp/consul-enterprise/dispatches"
